server:
  port: 8761
spring:
  cloud:
    config:
      server:
        git:
          uri: http://192.168.1.181:5102/sheip9/config-repo.git
          delete-untracked-branches: true
          default-label: main
        prefix: /config

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/