server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: lobby
  data:
    redis:
      host: localhost
      repositories:
        enabled: true
      client-type: lettuce
      #      cluster:
      #        nodes:
      #          - 192.168.1.192:6379
      timeout: 10000ms
      lettuce:
        pool:
          #?????
          max-active : 8
          #?????????????-1
          max-wait: 10000ms
          #?????????8
          max-idle: 200
          #?????????0
          min-idle: 5