server:
  port: 8082
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: lobby
    
apollo:
  bootstrap:
    namespaces: application.yml, cloudpvp-dev.eureka.yml, cloudpvp-dev.redis.yml