server:
  port: 8085
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: user-summary


apollo:
  bootstrap:
    namespaces: application.yml, cloudpvp-dev.eureka.yml