spring:
  data:
    redis:
      host: 192.168.1.192
      repositories:
        enabled: true
      client-type: lettuce
#      cluster:
#        nodes:
#          - 192.168.1.192:6379
#      timeout: 10000ms
#      lettuce:
#        pool:
#          #最大连接数
#          max-active : 8
#          #最大连接阻塞等待时间，默认-1
#          max-wait: 10000ms
#          #最大空闲连接，默认8
#          max-idle: 200
#          #最小空闲连接，默认0
#          min-idle: 5


eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.192:8761/eureka/