spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth
            uri:
              lb://auth
            predicates:
              - Path=/auth/**
          - id: matchmaking
            uri:
              lb://matchmaking
            predicates:
              - Path=/matchmaking/**
          - id: play
            uri:
              lb://play
            predicates:
              - Path=/play/**

eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/